sonar.organization=neovasili
sonar.projectKey=neovasili_2026-copilot-dev-day

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./demo/go/cmd,./demo/go/internal
sonar.go.coverage.reportPaths=./demo/go/coverage/coverage.out
sonar.coverage.exclusions=**/*_test.go,**/mocks.go
