sonar.organization=neovasili
sonar.projectKey=neovasili_2026-copilot-dev-day

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./internal
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=./coverage/coverage.out
sonar.coverage.exclusions=**/*_test.go,**/mocks.go
